feat: add missing getters
IPOR-Labs/ipor-protocol pull request #361
Opened 2022-12-15 18:42 UTC by alvaro-ipor

2022-12-15 20:11 UTC, mario-ipor requested changes

2022-12-15 20:11 UTC, mario-ipor commented on contracts/amm/MiltonInternal.sol
On top of smart contract external methods on bottom internal and private - try to not mix visibility in listed methods like here external internal external

2022-12-16 06:19 UTC, pete-ipor requested changes

2022-12-16 06:19 UTC, pete-ipor commented on contracts/interfaces/IJosephInternal.sol
> +    function getStanley() external view returns (address);
add documentations comments

2022-12-16 06:19 UTC, pete-ipor commented on contracts/interfaces/IMiltonInternal.sol
> +
add documentations comments

2022-12-16 06:19 UTC, pete-ipor commented on contracts/interfaces/IMiltonStorage.sol
> +    function getMilton() external view returns (address);
add documentations comments

2022-12-16 06:19 UTC, pete-ipor commented on contracts/interfaces/IStanleyInternal.sol
> +    function getIvToken() external view returns (address);
add documentations comments

2022-12-17 23:15 UTC, mario-ipor approved these changes

2022-12-19 12:46 UTC, merged