test: IporSwapLogic
IPOR-Labs/ipor-protocol pull request #369
Opened 2022-12-23 11:28 UTC by alvaro-ipor

2023-01-09 10:08 UTC, mario-ipor commented on test/utils/JosephUtils.sol
> +    ) public returns (ProxyTester, ItfJosephUsdt) {
Why you are return two values of the same smart contract instance?

2023-01-09 14:03 UTC, mario-ipor commented on test/utils/DataUtils.sol
> +        UsdtMockedToken tokenUsdt = new UsdtMockedToken(100000000000000 * 10 ** 6, 6);
Instead UsdtMockedToken use MockTestnetTokenUsdt

2023-01-09 18:50 UTC, mario-ipor commented on test/utils/MiltonUtils.sol
> +        vm.prank(miltonUsdtProxy);
miltonUsdtProxy is an owner of miltonUsdt ?

2023-01-23 08:12 UTC, pete-ipor requested changes

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        ItfIporOracle iporOracle = getIporOracleOneAsset(_userOne, address(_daiMockedToken), 5 * 10 ** 16);
we can use 5e16 instead of 5*10**16

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase0MiltonDai.itfCloseSwapPayFixed(1, block.timestamp + TestConstants.PERIOD_50_DAYS_IN_SECONDS);
This line should be in the `given` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase0MiltonDai.itfCloseSwapReceiveFixed(1, block.timestamp + TestConstants.PERIOD_50_DAYS_IN_SECONDS);
This line should be in the `given` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +    function testShouldNotClosepositionWhenSwapDoesNotExist() public {
testShouldNotClosePositionWhenSwapDoesNotExist

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.pause();
This line should be in the 'given' section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        vm.expectRevert("Pausable: paused");
This line should be in the 'when' section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.pause();
This line should be in the `given` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.closeSwaps(payFixedSwapIds, receiveFixedSwapIds);
This line should be in the `when` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.pause();
This line should be in the `given` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.pause();
This line should be in the `given` section

2023-01-23 08:12 UTC, pete-ipor commented on test/milton/MiltonShouldNotClosePosition.t.sol
> +        mockCase3MiltonDai.pause();
This line should be in the `given` section

2023-03-21 12:58 UTC, closed without merging