Feature/il 2350
IPOR-Labs/ipor-protocol pull request #399
Opened 2023-02-01 15:30 UTC by alvaro-ipor

2023-02-07 11:16 UTC, pete-ipor commented on test/milton/MiltonFacadeDataProvider.t.sol
> +// SPDX-License-Identifier: UNLICENSED
I don't see this test.
```
it("should receive empty list of swaps when offset is equal to number of swaps", 
```

2023-02-07 16:07 UTC, alvaro-ipor commented on test/utils/SwapUtils.sol
> -                vm.prank(user);
I prank before calling the function in the actual test file instead of the utils

```
vm.startPrank(user);
iterateOpenSwapsPayFixed(...)
```

2023-02-07 16:07 UTC, alvaro-ipor commented on test/utils/SwapUtils.sol
> -                vm.prank(user);
I prank before calling the function in the actual test file instead of the utils

```
vm.startPrank(user);
iterateOpenSwapsPayFixed(...)
```

2023-02-07 16:08 UTC, alvaro-ipor commented on test/utils/SwapUtils.sol
> -            vm.prank(user);
I prank before calling the function in the actual test file instead of the utils

```
vm.startPrank(user);
iterateOpenSwapsPayFixed(...)
```

2023-02-07 17:03 UTC, mario-ipor requested changes

2023-02-07 17:03 UTC, mario-ipor commented on test/milton/MiltonFacadeDataProvider.t.sol
> +        mockCase0Josephs.mockCase0JosephUsdt.itfProvideLiquidity(TestConstants.USD_50_000_6DEC, block.timestamp);
This step not exists in old test!

2023-02-07 17:03 UTC, mario-ipor commented on test/milton/MiltonFacadeDataProvider.t.sol
> +        mockCase0Josephs.mockCase0JosephUsdc.itfProvideLiquidity(TestConstants.USD_50_000_6DEC, block.timestamp);
This step not exists in old test!

2023-02-07 17:03 UTC, mario-ipor commented on test/utils/SwapUtils.sol
> -                vm.prank(user);
use prank inside method not outside

2023-02-07 17:03 UTC, mario-ipor commented on test/utils/SwapUtils.sol
> -                vm.prank(user);
use prank inside method not outside

2023-02-07 17:03 UTC, mario-ipor commented on test/utils/SwapUtils.sol
> -            vm.prank(user);
use prank inside method not outside

2023-02-08 23:01 UTC, mario-ipor approved these changes

2023-02-09 08:09 UTC, merged