test: MiltonShouldClosePosition
IPOR-Labs/ipor-protocol pull request #402
Opened 2023-02-01 17:41 UTC by alvaro-ipor

2023-02-27 23:54 UTC, mario-ipor requested changes

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        mockCase0JosephDai.itfProvideLiquidity(TestConstants.USD_1_000_000_18DEC, block.timestamp);
This is not the same value in provide liquidity - check old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        mockCase0JosephDai.itfProvideLiquidity(TestConstants.USD_1_000_000_18DEC, block.timestamp);
This is not the same value in provide liquidity - check old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        for (uint256 i = 0; i < 10; ++i) {
In old test let i = volumePayFixed; i < volumePayFixed + volumeReceiveFixed; i++)

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        for (uint256 i = 0; i < 5; ++i) {
wrong loop check old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        }
Add additional assertion in this test which was used in old test ""should close 5 pay fixed, 5 receive fixed positions in one transaction - case 3, some of them are already closed, call static"

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +            receiveFixedSwapIds[i] = i + 1;
Wrong index because wrong loop interation - check old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        for (uint256 i = 0; i < 10; ++i) {
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +        for (uint256 i = 0; i < 5; ++i) {
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Change loop iteration like it is in old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Missing setCalculateQuoteReceiveFixed check old test

2023-02-27 23:54 UTC, mario-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
Missing test "should close position, DAI, when amount exceeds balance milton on DAI token" fix it

2023-02-28 17:42 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Missed test ""should close position, DAI, not owner, receive fixed, Milton lost, User earned < Collateral, 5 hours before maturity"" - why?

Line 1855 -> `testShouldClosePositionDAIWhenReceiveFixedMiltonLostAndUserEarnedLessThanCollateralFiveHoursBeforeMaturity18DecimalsAndNotOwner`

2023-02-28 17:44 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Missed test "should close position, DAI, not owner, pay fixed, Milton lost, User earned > Collateral, after maturity" - why??

Line 1274 -> `testShouldClosePositionDAIWhenPayFixedMiltonLostAndUserEarnedLessThanCollateralAfterMaturity18DecimalsAndNotOwner`

2023-02-28 17:46 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Reference

Line 1031 -> `testShouldClosePositionDAIWhenPayFixedMiltonLostAndUserEarnedMoreThanCollateralAfterMaturity18DecimalsAndNotOwner`

2023-02-28 17:47 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Missed test ""should close position, DAI, not owner, pay fixed, Milton lost, User earned < Collateral, after maturity"" - why?

Line 1274 -> testShouldClosePositionDAIWhenPayFixedMiltonLostAndUserEarnedLessThanCollateralAfterMaturity18DecimalsAndNotOwner

2023-02-28 17:48 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Missed test ""should close position, DAI, not owner, pay fixed, Milton earned, User lost > Collateral, before maturity"" - why?

Line 135 -> `testShouldClosePositionDAIWhenPayFixedMiltonEarnedAndUserLostMoreThanCollateralBeforeMaturity18DecimalsAndNotOwner`

2023-02-28 17:49 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +
> Missed test: ""should close position, DAI, not owner, pay fixed, Milton earned, User lost < Collateral, after maturity"" - why?

Line 628 -> `testShouldClosePositionDAIWhenPayFixedMiltonEarnedAndUserLostLessThanCollateralAfterMaturity18DecimalsAndNotOwner`

2023-02-28 18:53 UTC, alvaro-ipor commented on test/milton/MiltonShouldClosePosition.t.sol
> +    function testShouldCalculatePayFixedPositionValueSimpleCase1() public {
Line 1691. -> `testShouldClosePositionDAIWhenPayFixedMiltonEarnedAndUserLostMoreThanCollateralAfterMaturity18DecimalsAndOwner`

2023-03-06 21:14 UTC, mario-ipor requested changes

2023-03-07 09:41 UTC, mario-ipor approved these changes

2023-03-07 09:42 UTC, merged